'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

export default function HomeExperience(){
  const [email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState('email'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const [games,setGames]=useState([]);const router=useRouter();
  useEffect(()=>{fetch('/api/auth/session').then(response=>{if(response.ok)setStage('authenticated')}).catch(()=>{});fetch('/api/game-hub').then(r=>r.json()).then(data=>setGames(data.games||[])).catch(()=>{});},[]);
  const next=games.find(game=>game.pick_status==='OPEN')||games[0];
  async function identify(event){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/auth/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const body=await response.json();if(!response.ok)setMessage(body.message||'Sign-in is temporarily unavailable.');else{setStage('code');setMessage(body.message)}}catch{setMessage('Sign-in is temporarily unavailable.')}finally{setBusy(false)}}
  async function verify(event){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const body=await response.json();if(!response.ok)setMessage(body.message||'The code is invalid or expired.');else router.push('/lineup')}catch{setMessage('Verification is temporarily unavailable.')}finally{setBusy(false)}}
  return <>
    <section className="homeHero"><div><p className="eyebrow">2026 PV FANTASY FOOTBALL</p><h1>Your eight.<br/><em>Your game.</em></h1><p>Build a balanced offense and defense from Prairie View’s roster, then follow every fantasy point.</p></div>{next&&<article className="nextGame"><span>{next.week} • {next.site}</span><strong>PV vs {next.opponent}</strong><small>{next.kickoff_ct}</small><b className={next.pick_status==='OPEN'?'statusOpen':'statusLocked'}>{next.pick_status}</b></article>}</section>
    <section className="identifyCard"><div><p className="eyebrow">SECURE SIGN-IN</p><h2>{stage==='code'?'Enter your code':stage==='authenticated'?'You’re signed in':'Verify your entry'}</h2><p>{stage==='code'?'Check the registered inbox. Codes expire in 10 minutes.':stage==='authenticated'?'Your secure participant session is active.':'We’ll email a one-time code if the address is registered.'}</p></div>{stage==='authenticated'?<button onClick={()=>router.push('/lineup')}>Continue to lineup</button>:<form onSubmit={stage==='code'?verify:identify}><label><span>{stage==='code'?'Verification code':'Email'}</span><input required type={stage==='code'?'text':'email'} inputMode={stage==='code'?'numeric':undefined} autoComplete={stage==='code'?'one-time-code':'email'} value={stage==='code'?code:email} onChange={event=>stage==='code'?setCode(event.target.value.replace(/\D/g,'').slice(0,6)):setEmail(event.target.value)} placeholder={stage==='code'?'000000':'you@example.com'}/></label><button disabled={busy}>{busy?'Please wait…':stage==='code'?'Verify and continue':'Send secure code'}</button>{message&&<small>{message}</small>}</form>}</section>
    <section className="howGrid"><article><b>01</b><h3>Pick a game</h3><p>See the opponent, kickoff, and live lineup deadline.</p></article><article><b>02</b><h3>Build eight</h3><p>Four offense and four defense. No duplicate players.</p></article><article><b>03</b><h3>Track results</h3><p>Follow player points, weekly rank, and season standings.</p></article></section>
  </>;
}
