import test from 'node:test';import assert from 'node:assert/strict';import {canonicalPosition,migrationCsv,parseOfficialRosterHtml,reconcilePvRoster} from '../lib/pv-roster-reconciliation.mjs';

test('parses official SIDEARM roster identity fields',()=>{const html='<li class="sidearm-roster-player" data-player-id="10"><span class="sidearm-roster-player-position"><span class="text-bold">RB</span></span><a aria-label="Kevin Brown, Jr. - View Full Bio">Bio</a><td class="roster_jerseynum ">7</td></li>';assert.deepEqual(parseOfficialRosterHtml(html).map(({rpId,name,position,jersey})=>({rpId,name,position,jersey})),[{rpId:'10',name:'Kevin Brown, Jr.',position:'RB',jersey:'7'}]);});

test('reconciles changes while preserving permanent PV IDs',()=>{const previous=[{rpId:'1',name:'A One',position:'WR',jersey:''},{rpId:'2',name:'B Two, Jr.',position:'LB',jersey:'4'},{rpId:'3',name:'Gone Player',position:'DB',jersey:'9'}];const current=[{rpId:'1',name:'A One',position:'RB',jersey:'7'},{rpId:'22',name:'B Two Jr',position:'LB',jersey:'5'},{rpId:'4',name:'New Player',position:'TE',jersey:'7'}];const canonical=[{playerId:'P1',name:'A One',position:'WR'},{playerId:'P2',name:'B Two, Jr.',position:'LB'},{playerId:'P3',name:'Gone Player',position:'DB'}];const mappings=[{'PV Player ID':'P1','Provider/Stable Identifier':'sidearm_roster_rp_id:1'},{'PV Player ID':'P2','Provider/Stable Identifier':'sidearm_roster_rp_id:2'}];const result=reconcilePvRoster({current,previous,canonical,mappings});assert.equal(result.status,'PROVISIONAL_FALL_CAMP');assert.equal(result.counts.newPlayers,1);assert.equal(result.counts.removedPlayers,1);assert.equal(result.counts.newJerseys,1);assert.equal(result.counts.jerseyChanges,1);assert.equal(result.counts.positionChanges,1);assert.equal(result.counts.formalNameChanges,1);assert.equal(result.counts.suffixPunctuationChanges,1);assert.equal(result.counts.rpIdChanges,1);assert.equal(result.counts.duplicateJerseys,1);assert.equal(result.migration.find(row=>row.name==='A One').pvPlayerId,'P1');assert.equal(result.migration.find(row=>row.name==='New Player').identityStatus,'NEW_PV_ID_REQUIRED');assert.equal(result.migration.find(row=>row.pvPlayerId==='P3').activeProposal,'REVIEW_INACTIVE_AFTER_FINAL_ROSTER');assert.ok(result.migration.every(row=>row.approval==='REQUIRED'));});

test('migration output is approval-gated and never invents a PV ID',()=>{const csv=migrationCsv([{pvPlayerId:'',name:'New',position:'RB',activeProposal:'ACTIVE_2026_PROPOSED',rosterRpId:'9',identityStatus:'NEW_PV_ID_REQUIRED',provenance:'official',approval:'REQUIRED'}]);assert.match(csv,/NEW_PV_ID_REQUIRED/);assert.match(csv,/REQUIRED/);});

test('canonicalizes official position labels without changing eligibility rules',()=>{assert.equal(canonicalPosition('Defensive Lineman'),'DL');assert.equal(canonicalPosition('Safety'),'DB');assert.equal(canonicalPosition('Punter'),'K/P');assert.equal(canonicalPosition('ATH'),'ATH');});
