import SiteHeader from '../components/SiteHeader';

const offense=[['Rushing touchdown','6 pts'],['Rushing yard','0.1 pt'],['Receiving touchdown','6 pts'],['Reception','0.5 pt'],['Receiving yard','0.1 pt'],['Interception thrown','−2 pts'],['Fumble lost','−2 pts']];
const defense=[['Tackle','0.5 pt'],['Tackle for loss','1 pt'],['Sack','2 pts'],['QB hurry / pass breakup','1 pt'],['Interception','2 pts'],['Forced fumble','1 pt'],['Fumble recovery','1 pt'],['Defensive return touchdown','6 pts'],['Negative yard created by TFL, sack, or interception','0.1 pt / yard']];
function RuleList({title,rules}){return <section className="ruleCard"><h2>{title}</h2><dl>{rules.map(([label,value])=><div key={label}><dt>{label}</dt><dd className={value.startsWith('−')?'penalty':''}>{value}</dd></div>)}</dl></section>}
const terms=[
  ['Eligibility and accounts','Participation is limited to people permitted by the organizer. Each person may maintain one account and must provide an email they control. Accounts and sessions may not be shared, transferred, automated, or used to impersonate another participant.'],
  ['Fantasy Team Name','Choose a 3–32 character public team name that complies with the registration character rules and is not deceptive, abusive, infringing, or confusingly similar to another participant. Conflicts may be held for organizer review.'],
  ['Lineups and player eligibility','Each game lineup contains exactly RB, WR, TE, Offensive Flex, DL, LB, DB, and Defensive Flex. A player may be used once. Only players shown as eligible by the authoritative PV Fantasy player registry may fill a slot.'],
  ['Deadline and replacement','A lineup must be authoritatively accepted before the displayed lock deadline. Participants may replace a lineup while entry remains open; only the newest accepted scoring version counts. Rejected, incomplete, late, superseded, or non-scoring versions never score.'],
  ['Scores and corrections','Live scores are provisional. Final scores become official only after official-source statistics, identity matching, required fallbacks, reconciliation, scoring gates, and publication controls pass. Later official stat corrections may change player, weekly, or cumulative totals.'],
  ['Official authority','PV Fantasy uses its certified scoring rules, authoritative workbook records, official event statistics, and documented reconciliation process. When sources conflict or data is incomplete, publication remains on hold until the organizer resolves the discrepancy.'],
  ['Fair play and security','Do not manipulate requests, evade limits, interfere with another account or lineup, scrape abusively, exploit defects, or attempt unauthorized access. The organizer may suspend affected access and preserve audit evidence.'],
  ['Technical corrections','The organizer may correct technical, identity, schedule, feed, scoring, or data-entry errors to restore the documented rules and authoritative record. Corrections must not create an undisclosed scoring rule change.'],
  ['Privacy and data use','Registration collects formal name, email, public Fantasy Team Name, terms acceptance, authentication/session records, lineups, and scoring history. This information is used to operate, secure, audit, support, and communicate about PV Fantasy. Public views use the Fantasy Team Name, not email or canonical Participant ID. Operational records may be retained as needed for integrity and support.'],
];
export default function Rules(){return <main className="publicPage"><SiteHeader/><section className="contentShell"><div className="pageIntro compactIntro"><p className="eyebrow">PVFF-1.0 • OFFICIAL RULES & TERMS</p><h1>RULES & SCORING</h1><p>Effective August 26, 2026. Registration acceptance records this version.</p></div><div className="rulesGrid"><RuleList title="OFFENSE" rules={offense}/><RuleList title="DEFENSE" rules={defense}/></div><aside className="rulesNotice"><strong>Important scoring notes</strong><ul><li>Offensive fumbles means fumbles lost—not total fumbles.</li><li>Kick-return and punt-return touchdowns do not earn fantasy touchdown points.</li><li>A weekly score is the sum of exactly eight accepted scoring-version picks.</li><li>Live scores remain provisional until official statistics and reconciliation are complete.</li></ul></aside><div className="termsSections"><h2>OFFICIAL PARTICIPATION TERMS</h2>{terms.map(([title,copy],index)=><section key={title}><b>{index+1}. {title}</b><p>{copy}</p></section>)}</div><aside className="rulesNotice"><strong>No prize or paid-entry terms</strong><p>PVFF-1.0 does not establish a paid entry, wager, or prize. Any future promotion requires separate written terms and does not alter these scoring rules.</p></aside><a className="buttonLink primaryLink" href="/lineup">Build my lineup →</a></section></main>}
