'use client';
import {useEffect,useMemo,useState} from 'react';
import SiteHeader from '../components/SiteHeader';
import {LINEUP_SLOTS,centralKickoffEpoch,playerLabel,submissionOutcome,validateLineupDraft} from '../../lib/participant-experience.mjs';

const GROUPS=[['OFFENSE',['RB','WR','TE','Offensive Flex']],['DEFENSE',['DL','LB','DB','Defensive Flex']]];
const parseKickoff=centralKickoffEpoch;
function deadlineText(game,now){if(!game)return'';if(game.pick_status!=='OPEN')return'Lineup locked';const kickoff=parseKickoff(game.kickoff_ct);if(!kickoff)return'Open until kickoff';const distance=kickoff-now;if(distance<=0)return'Lineup locked';const days=Math.floor(distance/86400000),hours=Math.floor(distance/3600000)%24,minutes=Math.floor(distance/60000)%60;return`${days?`${days}d `:''}${hours}h ${minutes}m until lock`;}
const shortSlot={'Offensive Flex':'FLEX','Defensive Flex':'D-FLEX'};

export default function LineupBuilder(){
  const [players,setPlayers]=useState([]),[games,setGames]=useState([]),[gameId,setGameId]=useState(''),[picks,setPicks]=useState({}),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[outcome,setOutcome]=useState(null),[loadError,setLoadError]=useState(''),[currentLineup,setCurrentLineup]=useState(null),[now,setNow]=useState(Date.now());
  useEffect(()=>{Promise.all([fetch('/api/auth/session'),fetch('/api/players').then(async r=>{if(!r.ok)throw new Error();return r.json()}),fetch('/api/game-hub').then(async r=>{if(!r.ok)throw new Error();return r.json()}),fetch('/api/lineup/current').then(response=>response.ok?response.json():null).catch(()=>null)]).then(([session,playerData,gameData,current])=>{if(session.ok)setStep(2);const available=playerData.players||[];setPlayers(available);setGames(gameData.games||[]);if(!available.length)setLoadError('No eligible players are available yet. Lineup entry will remain unavailable until the approved player pool is loaded.');const open=(gameData.games||[]).find(game=>game.pick_status==='OPEN');if(current?.picks?.length===8){setCurrentLineup(current);setGameId(current.game_id);setPicks(Object.fromEntries(current.picks.map(item=>[item.slot,item.player_key])))}else if(open)setGameId(open.game_id)}).catch(()=>setLoadError('The live player pool or schedule is unavailable. Please retry shortly.'));const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
  const game=games.find(item=>item.game_id===gameId);const used=useMemo(()=>new Set(Object.values(picks).filter(Boolean)),[picks]);const draft=validateLineupDraft(picks);const completed=used.size;const locked=!game||game.pick_status!=='OPEN'||(parseKickoff(game.kickoff_ct)!==null&&parseKickoff(game.kickoff_ct)<=now);
  function choose(slot,value){setPicks(current=>({...current,[slot]:value}));setOutcome(null)}
  function continueToReview(){const check=validateLineupDraft(picks);if(!check.valid)return setOutcome({state:check.code==='DUPLICATE_PLAYER'?'duplicate-error':'incomplete',title:check.code==='DUPLICATE_PLAYER'?'Player selected twice':'Complete all eight slots',message:check.message});setOutcome(null);setStep(4)}
  async function submit(){setBusy(true);setOutcome(null);try{const response=await fetch('/api/lineup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game_id:gameId,picks})});const data=await response.json().catch(()=>({}));const result={...submissionOutcome(data,response.ok),submittedAt:data.submitted_at||''};setOutcome(result);if(data.accepted)setStep(5)}catch{setOutcome(submissionOutcome({},false))}finally{setBusy(false)}}
  const selected=slot=>players.find(player=>player.player_key===picks[slot]);
  return <main className="publicPage"><SiteHeader/><section className="lineupShell"><div className="pageIntro compactIntro"><p className="eyebrow">ENTER YOUR LINEUP</p><h1>{step===5?'LINEUP CONFIRMED':'BUILD YOUR EIGHT'}</h1><div className="stepRail" aria-label="Lineup progress">{['Identify','Game','Lineup','Review','Done'].map((label,index)=><span className={step>=index+1?'active':''} key={label}>{label}</span>)}</div></div>
    {loadError&&<div className="stateMessage failure" role="alert"><strong>Unable to load lineup</strong><p>{loadError}</p></div>}
    {currentLineup&&<div className={`stateMessage ${currentLineup.state==='ACCEPTED_EDITABLE'?'success':'locked'}`} role="status"><strong>{currentLineup.state==='ACCEPTED_EDITABLE'?'Accepted lineup — editable':'Scoring lineup — locked'}</strong><p>{currentLineup.message}{currentLineup.replaced_previous?' Your earlier lineup was superseded by this accepted version.':''}</p></div>}
    {step===1&&<section className="flowCard"><h2>Secure sign-in required</h2><p>Verify your registered email before building or replacing a lineup.</p><a className="buttonLink" href="/">Sign in securely</a></section>}
    {step===2&&<section className="flowCard"><h2>Select game</h2><div className="gameList">{games.map(item=><button type="button" className={`gameChoice ${gameId===item.game_id?'selected':''}`} key={item.game_id} onClick={()=>setGameId(item.game_id)}><span>{item.week} • {item.site}</span><strong>PV vs {item.opponent}</strong><small>{item.kickoff_ct}</small><b className={item.pick_status==='OPEN'?'statusOpen':'statusLocked'}>{item.pick_status}</b></button>)}</div>{game&&<div className={`deadline ${locked?'locked':'open'}`}>{deadlineText(game,now)}</div>}<button disabled={!gameId||locked} onClick={()=>setStep(3)}>Build this lineup</button></section>}
    {step===3&&<section className="flowCard lineupBuild"><div className="matchStrip"><div><span>{game?.week}</span><strong>PV vs {game?.opponent}</strong><small>{[game?.kickoff_ct,game?.location||game?.site].filter(Boolean).join(' • ')}</small></div><b className={locked?'statusLocked':'statusOpen'}>{deadlineText(game,now)}</b></div><div className="completionBlock"><div><strong>{completed} / 8 COMPLETE</strong><span>{completed===8?'Ready to review':'Select one eligible player for every slot'}</span></div><progress max="8" value={completed} aria-label={`${completed} of 8 lineup slots complete`}>{completed}/8</progress></div>{GROUPS.map(([group,slots])=><div className="positionGroup" key={group}><h2>{group}</h2><div className="slotGrid">{slots.map(slot=>{const player=selected(slot);return <label className={`slot ${player?'filled':''}`} key={slot}><b className="slotBadge">{shortSlot[slot]||slot}</b><span><small>{slot}</small><strong>{player?.display_name||'Choose player'}</strong>{player&&<em>{[player.position,player.jersey?`#${player.jersey}`:''].filter(Boolean).join(' • ')}</em>}</span><select aria-label={`${slot} player`} disabled={locked} value={picks[slot]||''} onChange={event=>choose(slot,event.target.value)}><option value="">Select player</option>{players.filter(candidate=>candidate.eligible_slots.includes(slot)).map(candidate=>{const unavailable=used.has(candidate.player_key)&&picks[slot]!==candidate.player_key;return <option disabled={unavailable} key={candidate.player_key} value={candidate.player_key}>{playerLabel(candidate)}{unavailable?' • Selected':''}</option>})}</select></label>})}</div></div>)}<button disabled={locked||!draft.valid} onClick={continueToReview}>Review lineup <span aria-hidden="true">→</span></button></section>}
    {step===4&&<section className="flowCard"><div className="matchStrip"><div><span>REVIEW • {game?.week}</span><strong>PV vs {game?.opponent}</strong><small>{game?.kickoff_ct}</small></div><b className={locked?'statusLocked':'statusOpen'}>{deadlineText(game,now)}</b></div><div className="reviewList">{LINEUP_SLOTS.map(slot=>{const player=selected(slot);return <article key={slot}><span>{slot}</span><div><strong>{player?.display_name}</strong><small>{[player?.position,player?.jersey?`#${player.jersey}`:''].filter(Boolean).join(' • ')}</small></div></article>})}</div><div className="buttonRow"><button className="secondaryButton" onClick={()=>setStep(3)}>Edit lineup</button><button disabled={busy||locked||!draft.valid} onClick={submit}>{busy?'Confirming…':'Submit lineup'}</button></div><p className="acceptanceNote">Your lineup is saved only after the authoritative system confirms acceptance.</p></section>}
    {step===5&&<section className="flowCard confirmation" aria-live="polite"><div className={`confirmationMark ${outcome?.state}`} aria-hidden="true">✓</div><p className="eyebrow">AUTHORITATIVE ACCEPTANCE</p><h2>{outcome?.title}</h2><p>{outcome?.message}</p><div className="confirmationMeta"><span>{game?.week} MATCHUP</span><strong>PV <em>VS</em> {game?.opponent}</strong><small>{[game?.kickoff_ct,game?.location||game?.site].filter(Boolean).join(' • ')}</small>{outcome?.submittedAt&&<small>Submitted: {new Date(outcome.submittedAt).toLocaleString()}</small>}</div><div className="reviewList confirmationLineup">{LINEUP_SLOTS.map(slot=>{const player=selected(slot);return <article key={slot}><span>{slot}</span><div><strong>{player?.display_name}</strong><small>{[player?.position,player?.jersey?`#${player.jersey}`:''].filter(Boolean).join(' • ')}</small></div></article>})}</div><div className={`deadline ${locked?'locked':'open'}`}>{locked?'This lineup is locked':deadlineText(game,now)}</div><div className="buttonRow"><button className="secondaryButton" onClick={()=>setStep(4)}>View accepted lineup</button><button disabled={locked} onClick={()=>{setStep(3);setOutcome(null)}}>Edit before lock</button></div><p className="acceptanceNote">The latest lineup accepted before lock is the only lineup that scores. Changes are allowed only while the authoritative window remains open.</p></section>}
    {outcome&&step!==5&&<div className={`stateMessage ${outcome.state}`} role="status"><strong>{outcome.title}</strong><p>{outcome.message}</p></div>}
  </section></main>;
}
